module.exports=[
    {
        id:101,
        imgUrl:'../../images/item1.jpg',
        title:'美容养颜',
        type:0
    },
    {
        id:102,
        imgUrl:'../../images/item2.jpg',
        title:'美容养',
        type:1
    },
    {
        id:103,
        imgUrl:'../../images/item3.jpg',
        title:'美容养',
        type:2
    },
    {
        id:104,
        imgUrl:'../../images/item4.jpg',
        title:'美容养',
        type:3
    },
    {
        id:105,
        imgUrl:'../../images/item5.jpg',
        title:'美容养',
        type:4
    },
    {
        id:106,
        imgUrl:'../../images/item6.jpg',
        title:'美容养',
        type:5
    },
    {
        id:107,
        imgUrl:'../../images/item7.jpg',
        title:'美容养',
        type:6
    },
    {
        id:108,
        imgUrl:'../../images/item8.jpg',
        title:'美容养',
        type:7
    }
]